/** AUTO-GENERATED by scripts/build-promo-frames.mjs — do not edit by hand. */
export const PROMO_FPS = 12
export const PROMO_FRAME_COUNT = 485
export type PromoStageKey = "origin" | "air" | "ocean" | "road" | "warehouse"
export const promoStageFrames: { key: PromoStageKey; start: number; end: number }[] = [
  {
    "key": "origin",
    "start": 0,
    "end": 96
  },
  {
    "key": "air",
    "start": 97,
    "end": 193
  },
  {
    "key": "ocean",
    "start": 194,
    "end": 290
  },
  {
    "key": "road",
    "start": 291,
    "end": 387
  },
  {
    "key": "warehouse",
    "start": 388,
    "end": 484
  }
]
export function promoFrameSrc(index: number, small: boolean): string {
  const name = "f-" + String(index + 1).padStart(4, "0") + ".webp"
  return (small ? "/promo/sm/" : "/promo/") + name
}
