"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowRight, Clock3, LockKeyhole, Radar } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { apiJson } from "@/lib/api-client"

type Locale = "zh" | "en"
type Request = { id: string; route?: { origin?: string; destination?: string }; cargo_details?: { cargo?: string; cargo_type?: string; mode?: string }; services_needed?: string[]; bid_deadline?: string; status?: string }
const copy = { zh: { empty: "目前沒有開放競價的需求。", load: "正在掃描可投標任務", mission: "SEALED BID", open: "競價進行中", bid: "進入 Bid Mode", sealed: "所有競爭對手資料均保持密封。", final: "FINAL WINDOW" }, en: { empty: "There are no open bid opportunities right now.", load: "Scanning bid missions", mission: "SEALED BID", open: "Bidding open", bid: "Enter Bid Mode", sealed: "All competitor details remain sealed.", final: "FINAL WINDOW" } }

export function LiveMarketplaceList({ locale }: { locale: Locale }) { const t = copy[locale]; const [requests, setRequests] = useState<Request[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { let active = true; apiJson("/api/shipment-requests").then(({ response, body }) => { if (!active) return; if (!response.ok) setError(body.error || t.empty); else setRequests((body.shipmentRequests || []).filter((request: Request) => request.status === "OPEN")); setLoading(false) }); return () => { active = false } }, [t.empty]); if (loading) return <p className="mt-6 text-sm text-slate-500">{t.load}</p>; if (error || !requests.length) return <p className="mt-6 border border-dashed border-lblue/15 bg-white p-8 text-center text-sm text-slate-500">{error || t.empty}</p>; return <section className="mt-6 grid gap-4 lg:grid-cols-2">{requests.map((request) => <MissionCard key={request.id} locale={locale} request={request} t={t} />)}</section> }
function MissionCard({ locale, request, t }: { locale: Locale; request: Request; t: typeof copy.zh }) { const countdown = useCountdown(request.bid_deadline); const final = countdown.total > 0 && countdown.total <= 15 * 60 * 1000; const route = `${request.route?.origin || "-"} → ${request.route?.destination || "Hong Kong"}`; const cargo = request.cargo_details?.cargo || request.cargo_details?.cargo_type || "-"; return <Card className={`mission-list-card ${final ? "mission-list-card-final" : ""}`}><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge variant="gold">{t.mission}</Badge><Badge variant="teal">{t.open}</Badge>{final ? <Badge variant="secondary">{t.final}</Badge> : null}</div><h2 className="mt-4 text-xl font-semibold text-lblue">{route}</h2><p className="mt-1 text-sm text-slate-600">{cargo}</p></div><div className="text-right"><Clock3 className="ml-auto h-4 w-4 text-[#b18a25]" /><p className="mt-1 font-mono text-lg font-semibold text-lblue">{countdown.label}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-[#edf0f4] pt-4"><p className="flex items-center gap-2 text-xs text-slate-500"><LockKeyhole className="h-4 w-4 text-[#b18a25]" />{t.sealed}</p><Button asChild size="sm" variant="gold"><Link href={`/${locale}/marketplace/${request.id}`}><Radar className="h-4 w-4" />{t.bid}<ArrowRight className="h-4 w-4" /></Link></Button></div></CardContent></Card> }
function useCountdown(deadline?: string) { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer) }, []); const total = Math.max(0, deadline ? new Date(deadline).getTime() - now : 0); const h = Math.floor(total / 3600000); const m = Math.floor((total % 3600000) / 60000); const s = Math.floor((total % 60000) / 1000); return { total, label: `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}` } }
