import React from "react"
import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer"
import { NextResponse } from "next/server"

import { getApiSupabaseServiceClient, getApiSupabaseSession, isSupabaseConfigured } from "@/lib/supabase/api"

const styles = StyleSheet.create({
  page: { padding: 34, fontSize: 10, color: "#1B2B5E", fontFamily: "Helvetica" },
  header: { borderBottomWidth: 1, borderBottomColor: "#C9A84C", paddingBottom: 14, marginBottom: 18 },
  brand: { fontSize: 24, fontWeight: 700, letterSpacing: 2 },
  subtitle: { marginTop: 6, color: "#64748b" },
  grid: { display: "flex", flexDirection: "row", gap: 10, marginBottom: 12 },
  box: { flex: 1, borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 6, padding: 10 },
  label: { color: "#64748b", fontSize: 8, textTransform: "uppercase", marginBottom: 4 },
  value: { fontSize: 11, fontWeight: 700, lineHeight: 1.4 },
  note: { marginTop: 18, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#e2e8f0", color: "#64748b", lineHeight: 1.5 },
})

export async function POST(request: Request, { params }: { params: { id: string } }) {
  const session = await getApiSupabaseSession(request)
  const body = await request.json().catch(() => ({}))
  const awb = normalizeAwb(body, params.id)
  const buffer = await buildAwbPdf(awb)

  if (!session) {
    if (isSupabaseConfigured()) return NextResponse.json({ error: "UNAUTHENTICATED" }, { status: 401 })
    return pdfResponse(buffer, params.id)
  }

  const service = getApiSupabaseServiceClient()
  if (!service) return NextResponse.json({ error: "SUPABASE_SERVICE_NOT_CONFIGURED" }, { status: 500 })

  const path = `${params.id}/awb-${crypto.randomUUID()}.pdf`
  const { error: uploadError } = await service.storage.from("documents").upload(path, buffer, {
    contentType: "application/pdf",
    upsert: false,
  })

  if (uploadError) return NextResponse.json({ error: uploadError.message, bucket: "documents" }, { status: 500 })

  const { data: publicData } = service.storage.from("documents").getPublicUrl(path)
  const { data, error } = await session.supabase.from("documents").insert({
    order_id: params.id,
    type: "AWB",
    file_url: publicData.publicUrl,
    uploaded_by: session.user.id,
  }).select("id, order_id, type, file_url, uploaded_by, created_at").single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ ok: true, awb, document: data, pdfUrl: publicData.publicUrl }, { status: 201 })
}

async function buildAwbPdf(awb: ReturnType<typeof normalizeAwb>) {
  const pdf = React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(View, { style: styles.header },
        React.createElement(Text, { style: styles.brand }, "LBID"),
        React.createElement(Text, { style: styles.subtitle }, "Standardised AWB draft"),
      ),
      React.createElement(View, { style: styles.grid },
        React.createElement(Box, { label: "AWB Ref", value: awb.reference }),
        React.createElement(Box, { label: "Route", value: awb.route }),
        React.createElement(Box, { label: "Chargeable", value: `${awb.chargeableWeight} kg` }),
      ),
      React.createElement(View, { style: styles.grid },
        React.createElement(Box, { label: "Shipper", value: awb.shipper }),
        React.createElement(Box, { label: "Consignee", value: awb.consignee }),
      ),
      React.createElement(View, { style: styles.grid },
        React.createElement(Box, { label: "Pieces", value: String(awb.pieces) }),
        React.createElement(Box, { label: "Gross weight", value: `${awb.grossWeight} kg` }),
        React.createElement(Box, { label: "Volumetric", value: `${awb.volumetricWeight} kg` }),
      ),
      React.createElement(View, { style: styles.grid },
        React.createElement(Box, { label: "Commodity", value: awb.commodity }),
        React.createElement(Box, { label: "Handling", value: awb.handling }),
      ),
      React.createElement(Text, { style: styles.note }, "Generated by LBID Smart AWB. This draft supports document workflow and must be validated against airline/carrier requirements before final issue."),
    ),
  )

  return renderToBuffer(pdf)
}

function Box({ label, value }: { label: string; value: string }) {
  return React.createElement(View, { style: styles.box },
    React.createElement(Text, { style: styles.label }, label),
    React.createElement(Text, { style: styles.value }, value),
  )
}

function normalizeAwb(body: any, orderId: string) {
  const pieces = Number(body.pieces || 1)
  const grossWeight = Number(body.grossWeight || body.gross || 0)
  const length = Number(body.length || 0)
  const width = Number(body.width || 0)
  const height = Number(body.height || 0)
  const volumetricWeight = Math.ceil((length * width * height * pieces) / 6000)
  return {
    reference: `AWB-${orderId.slice(-6).toUpperCase()}`,
    route: body.route || body.airport || "BOM / HKG",
    shipper: body.shipper || "ABC Company, Mumbai, India",
    consignee: body.consignee || "Hong Kong Buyer Limited, Hong Kong",
    pieces,
    grossWeight,
    volumetricWeight,
    chargeableWeight: Math.max(grossWeight, volumetricWeight),
    commodity: body.commodity || "General cargo",
    handling: body.handling || "Handle with care",
  }
}

function pdfResponse(buffer: Buffer, orderId: string) {
  return new Response(buffer, {
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `inline; filename="LBID-AWB-${orderId}.pdf"`,
      "cache-control": "no-store",
    },
  })
}
